In [95]:
from pandas import Series

lista = ["Kraków", "Lublin", 15, 0.99, "c", object()]
s = Series(lista)
#print(s)
print(lista)
s

['Kraków', 'Lublin', 15, 0.99, 'c', <object object at 0x7f8d38a8f3c0>]

0                               Kraków
1                               Lublin
2                                   15
3                                 0.99
4                                    c
5    <object object at 0x7f8d38a8f3c0>
dtype: object

In [98]:
ids = ["A", "B", "A", "B", "A", "B"]
s = Series(lista, ids)
print(s)

A                               Kraków
B                               Lublin
A                                   15
B                                 0.99
A                                    c
B    <object object at 0x7f8d38a8f3c0>
dtype: object

In [102]:
#d = {"Kraków": 1500, "Zabierzów": 789, "Zabierzów": 532, "Trzebinia": 950, "Wieliczka": -998, "Krzeszowice": None}
a = ["Kraków", "Zabierzów", "Zabierzów", "Trzebinia", "Wieliczka", "Krzeszowice"]
b = [1500, 789, 532, 950, -998, None]
s = Series(b, a)
print(s)

Kraków         1500.0
Zabierzów       789.0
Zabierzów       532.0
Trzebinia       950.0
Wieliczka      -998.0
Krzeszowice       NaN
dtype: float64

In [103]:
print(s["Kraków"])
print("-----")
l = ["Zabierzów", "Wieliczka", "Krzeszowice"]
ns = s[l]
print(ns)
print(type(ns))

1500.0
-----
Zabierzów      789.0
Zabierzów      532.0
Wieliczka     -998.0
Krzeszowice      NaN
dtype: float64
<class 'pandas.core.series.Series'>

In [107]:
sl = s < 950
print(sl)

Kraków         False
Zabierzów       True
Zabierzów       True
Trzebinia      False
Wieliczka       True
Krzeszowice    False
dtype: bool

In [111]:
sl = s[s < 900]
sl

Zabierzów    789.0
Zabierzów    532.0
Wieliczka   -998.0
dtype: float64

In [113]:
print(s[{ "Zabierzów": 0, "Trzebinia": True, "Wieliczka": False}])

Zabierzów    789.0
Zabierzów    532.0
Trzebinia    950.0
Wieliczka   -998.0
dtype: float64

In [116]:
s[s < 900] = 200
s["Zabierzów"] = 100

print(s)

Kraków         2000.0
Zabierzów       100.0
Zabierzów       100.0
Trzebinia       950.0
Wieliczka       200.0
Krzeszowice       NaN
dtype: float64

In [117]:
print("Krzeszowice" in s, "Zabierzów" in s, 950 in s.values)

True True True

In [118]:
from math import pi
print(s * pi)

Kraków         6283.185307
Zabierzów       314.159265
Zabierzów       314.159265
Trzebinia      2984.513021
Wieliczka       628.318531
Krzeszowice            NaN
dtype: float64

In [124]:
a = ["Zakopane", "Nowy Targ", "Wieliczka", "Krzeszowice", "Zabierzów", "Zabierzów"]
b = [350, None, 200, 300, 100, 200]
t = Series(b, a)
s["Krzeszowice"] = 100
print(t)
print(s)
print(s + t)

Zakopane       350.0
Nowy Targ        NaN
Wieliczka      200.0
Krzeszowice    300.0
Zabierzów      100.0
Zabierzów      200.0
dtype: float64
Kraków         2000.0
Zabierzów       100.0
Zabierzów       100.0
Trzebinia       950.0
Wieliczka       200.0
Krzeszowice     100.0
dtype: float64
Kraków           NaN
Krzeszowice    400.0
Nowy Targ        NaN
Trzebinia        NaN
Wieliczka      400.0
Zabierzów      200.0
Zabierzów      300.0
Zabierzów      200.0
Zabierzów      300.0
Zakopane         NaN
dtype: float64

In [ ]:
print(s)

In [126]:
s["Krzeszowice"] = None
print(s.notnull())

Kraków          True
Zabierzów       True
Zabierzów       True
Trzebinia       True
Wieliczka       True
Krzeszowice    False
dtype: bool

In [127]:
print(t.isnull())

Zakopane       False
Nowy Targ       True
Wieliczka      False
Krzeszowice    False
Zabierzów      False
Zabierzów      False
dtype: bool

In [128]:
t["Krzeszowice"] = None
print(s+t)
b = (s+t).isnull()
print(b)
type(b)

Kraków           NaN
Krzeszowice      NaN
Nowy Targ        NaN
Trzebinia        NaN
Wieliczka      400.0
Zabierzów      200.0
Zabierzów      300.0
Zabierzów      200.0
Zabierzów      300.0
Zakopane         NaN
dtype: float64
Kraków          True
Krzeszowice     True
Nowy Targ       True
Trzebinia       True
Wieliczka      False
Zabierzów      False
Zabierzów      False
Zabierzów      False
Zabierzów      False
Zakopane        True
dtype: bool

pandas.core.series.Series

In [132]:
print(s)
print(s.iloc[1])

Kraków         2000.0
Zabierzów       100.0
Zabierzów       100.0
Trzebinia       950.0
Wieliczka       200.0
Krzeszowice       NaN
dtype: float64
100.0

In [125]:
print(s.add(t, fill_value=0))

Kraków         2000.0
Krzeszowice     400.0
Nowy Targ         NaN
Trzebinia       950.0
Wieliczka       400.0
Zabierzów       200.0
Zabierzów       300.0
Zabierzów       200.0
Zabierzów       300.0
Zakopane        350.0
dtype: float64

In [137]:
s = Series(d)
print(s.max())
print(s.mean())
l = ["Kraków", "Zabierzów", "Trzebinia", "Wieliczka"]
print(s[s > 900].mean())
s

1500.0
496.0
1225.0

Kraków         1500.0
Zabierzów       532.0
Trzebinia       950.0
Wieliczka      -998.0
Krzeszowice       NaN
dtype: float64

In [139]:
sv = Series([12, 12, 13, 14, 16, 19, 15, 13, 11, 9, 14, 10, 11, 12, 14, 18, 21, 19, 23])
print(sv)
sv.rolling(7).mean()

0     12
1     12
2     13
3     14
4     16
5     19
6     15
7     13
8     11
9      9
10    14
11    10
12    11
13    12
14    14
15    18
16    21
17    19
18    23
dtype: int64

0           NaN
1           NaN
2           NaN
3           NaN
4           NaN
5           NaN
6     14.428571
7     14.571429
8     14.428571
9     13.857143
10    13.857143
11    13.000000
12    11.857143
13    11.428571
14    11.571429
15    12.571429
16    14.285714
17    15.000000
18    16.857143
dtype: float64

In [141]:
sv.quantile([0, .33, .66, 1])

0.00     9.00
0.33    12.00
0.66    14.88
1.00    23.00
dtype: float64

In [144]:
sv.sample(25, replace=True)

3     14
4     16
3     14
8     11
10    14
0     12
17    19
8     11
8     11
6     15
15    18
13    12
1     12
3     14
1     12
18    23
2     13
16    21
9      9
11    10
8     11
16    21
2     13
0     12
11    10
dtype: int64

In [146]:
print(sv.to_csv(index_label="id", header=["val"]))

id,val
0,12
1,12
2,13
3,14
4,16
5,19
6,15
7,13
8,11
9,9
10,14
11,10
12,11
13,12
14,14
15,18
16,21
17,19
18,23

In [156]:
from pandas import DataFrame
dane = {'year': [2010, 2011, 2012, 2013, 2014, 2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022],
        'user1': [0, 0, 0, 0, 15, 49, 122, 341, 298, 319, 276, 307, 353],
        'user2': [743, 826, 756, 808, 634, 312, 95, 152, 112, 264, 317, 287, 172],
        'user3': [59, 91, 75, 158, 64, 49, 84, 78, 50, 68, 51, 108, 93]}
ac = DataFrame(dane, columns=['user1', 'user2', 'user3'], index = dane['year'])
ac

      user1  user2  user3
2010      0    743     59
2011      0    826     91
2012      0    756     75
2013      0    808    158
2014     15    634     64
2015     49    312     49
2016    122     95     84
2017    341    152     78
2018    298    112     50
2019    319    264     68
2020    276    317     51
2021    307    287    108
2022    353    172     93

In [157]:
for i in ac.index:
    print(f"Numer wiersza: {i}")
for c in ac.columns:
    print(f"Nazwa kolumny: {c}")

Numer wiersza: 2010
Numer wiersza: 2011
Numer wiersza: 2012
Numer wiersza: 2013
Numer wiersza: 2014
Numer wiersza: 2015
Numer wiersza: 2016
Numer wiersza: 2017
Numer wiersza: 2018
Numer wiersza: 2019
Numer wiersza: 2020
Numer wiersza: 2021
Numer wiersza: 2022
Nazwa kolumny: user1
Nazwa kolumny: user2
Nazwa kolumny: user3

In [159]:
print(ac.dtypes)
print(type(ac.iloc[1]))
print(ac.dtypes['user1'])

user1    int64
user2    int64
user3    int64
dtype: object
<class 'pandas.core.series.Series'>
int64

In [160]:
print(ac.shape)

(13, 3)

In [166]:
ac.tail()

      user1  user2  user3
2018    298    112     50
2019    319    264     68
2020    276    317     51
2021    307    287    108
2022    353    172     93

In [170]:
ac.at[2021, 'user2'] = 123
print(ac.at[2021, 'user2'])
print(ac.iat[10, 2])
print(ac.head(12))

123
51
      user1  user2  user3
2010      0    743     59
2011      0    826     91
2012      0    756     75
2013      0    808    158
2014     15    634     64
2015     49    312     49
2016    122     95     84
2017    341    152     78
2018    298    112     50
2019    319    264     68
2020    276    317     51
2021    307    123    108

In [171]:
ac.loc[2015:2020]

      user1  user2  user3
2015     49    312     49
2016    122     95     84
2017    341    152     78
2018    298    112     50
2019    319    264     68
2020    276    317     51

In [172]:
ac.iloc[2:10:2]

      user1  user2  user3
2012      0    756     75
2014     15    634     64
2016    122     95     84
2018    298    112     50

In [ ]:
ac

In [173]:
for label, content in ac.items():
    print(label)
    print(content)

user1
2010      0
2011      0
2012      0
2013      0
2014     15
2015     49
2016    122
2017    341
2018    298
2019    319
2020    276
2021    307
2022    353
Name: user1, dtype: int64
user2
2010    743
2011    826
2012    756
2013    808
2014    634
2015    312
2016     95
2017    152
2018    112
2019    264
2020    317
2021    123
2022    172
Name: user2, dtype: int64
user3
2010     59
2011     91
2012     75
2013    158
2014     64
2015     49
2016     84
2017     78
2018     50
2019     68
2020     51
2021    108
2022     93
Name: user3, dtype: int64

In [174]:
for content in ac:
    print(content)

user1
user2
user3

In [ ]:
print(ac.tail(10))

In [175]:
ac.where(ac > 250)
#print(ac)

      user1  user2  user3
2010    NaN  743.0    NaN
2011    NaN  826.0    NaN
2012    NaN  756.0    NaN
2013    NaN  808.0    NaN
2014    NaN  634.0    NaN
2015    NaN  312.0    NaN
2016    NaN    NaN    NaN
2017  341.0    NaN    NaN
2018  298.0    NaN    NaN
2019  319.0  264.0    NaN
2020  276.0  317.0    NaN
2021  307.0    NaN    NaN
2022  353.0    NaN    NaN

In [177]:
ac.mask(ac < 250, 0)

      user1  user2  user3
2010      0    743      0
2011      0    826      0
2012      0    756      0
2013      0    808      0
2014      0    634      0
2015      0    312      0
2016      0      0      0
2017    341      0      0
2018    298      0      0
2019    319    264      0
2020    276    317      0
2021    307      0      0
2022    353      0      0

In [178]:
print(ac.query('user1 > user2'))
print(ac[ac.user1 > ac.user2])

      user1  user2  user3
2016    122     95     84
2017    341    152     78
2018    298    112     50
2019    319    264     68
2021    307    123    108
2022    353    172     93
      user1  user2  user3
2016    122     95     84
2017    341    152     78
2018    298    112     50
2019    319    264     68
2021    307    123    108
2022    353    172     93

In [179]:
print(ac.tail(3) + 100)
print(ac.tail(3) * 3)
print(ac.tail(3) / 10)
print(ac.tail(3) // 2)
print(ac.tail(3) % 10)

      user1  user2  user3
2020    376    417    151
2021    407    223    208
2022    453    272    193
      user1  user2  user3
2020    828    951    153
2021    921    369    324
2022   1059    516    279
      user1  user2  user3
2020   27.6   31.7    5.1
2021   30.7   12.3   10.8
2022   35.3   17.2    9.3
      user1  user2  user3
2020    138    158     25
2021    153     61     54
2022    176     86     46
      user1  user2  user3
2020      6      7      1
2021      7      3      8
2022      3      2      3

In [ ]:
print(ac.apply(lambda x: x%100 if x.name == "year" else x))
ac

In [180]:
from pandas import DataFrame
salaries = {'stażysta': [2294, 2417, 2538], 
            'kontraktowy': [2361, 2487, 2611], 
            'mianowany': [2681, 2824, 2965], 
            'dyplomowany': [3149, 3317, 3483]}
factor = {'stażysta': [2, 2, 5], 
          'kontraktowy': [.5, .5, 1], 
          'mianowany': [2, 2, .5], 
          'dyplomowany': [2, 3, 4]}
years = [2017,2018,2019]
a = DataFrame(salaries, index=years)
b = DataFrame(factor, index=years)
print(a)
print(b)
print(a*b)

      stażysta  kontraktowy  mianowany  dyplomowany
2017      2294         2361       2681         3149
2018      2417         2487       2824         3317
2019      2538         2611       2965         3483
      stażysta  kontraktowy  mianowany  dyplomowany
2017         2          0.5        2.0            2
2018         2          0.5        2.0            3
2019         5          1.0        0.5            4
      stażysta  kontraktowy  mianowany  dyplomowany
2017      4588       1180.5     5362.0         6298
2018      4834       1243.5     5648.0         9951
2019     12690       2611.0     1482.5        13932

In [182]:
print(a.agg(['mean', 'max', 'min']))

         stażysta  kontraktowy    mianowany  dyplomowany
mean  2416.333333  2486.333333  2823.333333  3316.333333
max   2538.000000  2611.000000  2965.000000  3483.000000
min   2294.000000  2361.000000  2681.000000  3149.000000

In [183]:
dane = [1, 2, 3, 10, 20, 30, 100, 200, 300]
czas = [2017, 2018, 2019, 2017, 2018, 2019, 2017, 2018, 2019]
c = DataFrame({'date': czas, 'data': dane})
print(c)
print(c.groupby('date').sum())
print(c.groupby('date').transform('sum'))

   date  data
0  2017     1
1  2018     2
2  2019     3
3  2017    10
4  2018    20
5  2019    30
6  2017   100
7  2018   200
8  2019   300
      data
date
2017   111
2018   222
2019   333
   data
0   111
1   222
2   333
3   111
4   222
5   333
6   111
7   222
8   333

In [184]:
print(a.T)
print(a.T.std())

             2017  2018  2019
stażysta     2294  2417  2538
kontraktowy  2361  2487  2611
mianowany    2681  2824  2965
dyplomowany  3149  3317  3483
2017    390.261771
2018    410.900130
2019    431.538623
dtype: float64

In [185]:
print(c.drop_duplicates(subset='date'))
c

   date  data
0  2017     1
1  2018     2
2  2019     3

   date  data
0  2017     1
1  2018     2
2  2019     3
3  2017    10
4  2018    20
5  2019    30
6  2017   100
7  2018   200
8  2019   300

In [186]:
d = DataFrame([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
print("obiekt d:")
print(d)
print("transpozycja obiektu d:")
print(d.T)
print("mnożenie zwykłe")
print(d*d.T)
print("mnożenie macierzy d i d.T:")
print(d.dot(d.T))

obiekt d:
    0
0   1
1   2
2   3
3   4
4   5
5   6
6   7
7   8
8   9
9  10
transpozycja obiektu d:
   0  1  2  3  4  5  6  7  8   9
0  1  2  3  4  5  6  7  8  9  10
mnożenie zwykłe
     0   1   2   3   4   5   6   7   8   9
0  1.0 NaN NaN NaN NaN NaN NaN NaN NaN NaN
1  NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN
2  NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN
3  NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN
4  NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN
5  NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN
6  NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN
7  NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN
8  NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN
9  NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN
mnożenie macierzy d i d.T:
    0   1   2   3   4   5   6   7   8    9
0   1   2   3   4   5   6   7   8   9   10
1   2   4   6   8  10  12  14  16  18   20
2   3   6   9  12  15  18  21  24  27   30
3   4   8  12  16  20  24  28  32  36   40
4   5  10  15  20  25  30  35  40  45   50
5   6  12  18  24  30  36  42  48  54   60
6   7  14  21  28  35  42  49  56  63   70
7   8  16  24  32  40  48  56  64  72   80
8   9  18  27  36  45  54  63  72  81   90
9  10  20  30  40  50  60  70  80  90  100

In [ ]:
import numpy as np
macierz = d.dot(d.T).to_numpy()
print(macierz)
print(np.linalg.det(macierz))