In [1]:
from pandas import Series

lista = ["Kraków", "Lublin", 15, 0.99, "c", object()]
s = Series(lista)
#print(s)
print(lista)
s

['Kraków', 'Lublin', 15, 0.99, 'c', <object object at 0x7f930a1b24a0>]

0                               Kraków
1                               Lublin
2                                   15
3                                 0.99
4                                    c
5    <object object at 0x7f930a1b24a0>
dtype: object

In [2]:
ids = ["P", "Q", "R", "S", "T", "U"]
s = Series(lista, ids)
print(s)

P                               Kraków
Q                               Lublin
R                                   15
S                                 0.99
T                                    c
U    <object object at 0x7f930a1b24a0>
dtype: object

In [5]:
d = {"Kraków": 1500, "Zabierzów": 789, "Trzebinia": 950, "Wieliczka": -998, "Krzeszowice": None}
s = Series(d)
print(s)

Kraków         1500.0
Zabierzów       789.0
Trzebinia       950.0
Wieliczka      -998.0
Krzeszowice       NaN
dtype: float64

In [9]:
print(s["Kraków"])
print("-----")
l = ["Zabierzów", "Wieliczka", "Krzeszowice"]
ns = s[l]
print(type(ns))

1500.0
-----
<class 'pandas.core.series.Series'>

In [10]:
sl = s < 950
print(sl)

Kraków         False
Zabierzów       True
Trzebinia      False
Wieliczka       True
Krzeszowice    False
dtype: bool

In [11]:
sl = s[s < 900]
sl

Zabierzów    789.0
Wieliczka   -998.0
dtype: float64

In [12]:
print(s[{ "Zabierzów": False, "Kraków": False, "Trzebinia": True, "Wieliczka": False}])

Zabierzów     789.0
Kraków       1500.0
Trzebinia     950.0
Wieliczka    -998.0
dtype: float64

In [13]:
s["Kraków"] = 2000
s[s < 900] = 200

print(s)

Kraków         2000.0
Zabierzów       200.0
Trzebinia       950.0
Wieliczka       200.0
Krzeszowice       NaN
dtype: float64

In [14]:
print("Krzeszowice" in s, "Zakopane" in s, 950 in s.values)

True False True

In [15]:
from math import pi
print(s * pi)

Kraków         6283.185307
Zabierzów       628.318531
Trzebinia      2984.513021
Wieliczka       628.318531
Krzeszowice            NaN
dtype: float64

In [16]:
t = Series({"Zakopane": 350, "Nowy Targ": None, "Wieliczka": 200, "Krzeszowice": 300})
s["Krzeszowice"] = 100
print(t)
print(s)
print(s + t)

Zakopane       350.0
Nowy Targ        NaN
Wieliczka      200.0
Krzeszowice    300.0
dtype: float64
Kraków         2000.0
Zabierzów       200.0
Trzebinia       950.0
Wieliczka       200.0
Krzeszowice     100.0
dtype: float64
Kraków           NaN
Krzeszowice    400.0
Nowy Targ        NaN
Trzebinia        NaN
Wieliczka      400.0
Zabierzów        NaN
Zakopane         NaN
dtype: float64

In [ ]:
print(s)

In [17]:
s["Krzeszowice"] = None
print(s.notnull())

Kraków          True
Zabierzów       True
Trzebinia       True
Wieliczka       True
Krzeszowice    False
dtype: bool

In [18]:
print(t.isnull())

Zakopane       False
Nowy Targ       True
Wieliczka      False
Krzeszowice    False
dtype: bool

In [19]:
t["Krzeszowice"] = None
print(s+t)
b = (s+t).isnull()
print(b)
type(b)

Kraków           NaN
Krzeszowice      NaN
Nowy Targ        NaN
Trzebinia        NaN
Wieliczka      400.0
Zabierzów        NaN
Zakopane         NaN
dtype: float64
Kraków          True
Krzeszowice     True
Nowy Targ       True
Trzebinia       True
Wieliczka      False
Zabierzów       True
Zakopane        True
dtype: bool

pandas.core.series.Series

In [23]:
print((s+t).iloc[1])

nan

In [24]:
print(s.add(t, fill_value=0))

Kraków         2000.0
Krzeszowice       NaN
Nowy Targ         NaN
Trzebinia       950.0
Wieliczka       400.0
Zabierzów       200.0
Zakopane        350.0
dtype: float64

In [25]:
s = Series(d)
print(s.max())
print(s.mean())
print(s[["Kraków", "Zabierzów", "Trzebinia", "Wieliczka"]].mean())
s

1500.0
560.25
560.25

Kraków         1500.0
Zabierzów       789.0
Trzebinia       950.0
Wieliczka      -998.0
Krzeszowice       NaN
dtype: float64

In [28]:
sv = Series([12, 12, 13, 14, 16, 19, 15, 13, 11, 9, 14, 10, 11, 12, 14, 18, 21, 19, 23])
sv.rolling(7).mean()

0           NaN
1           NaN
2           NaN
3           NaN
4           NaN
5           NaN
6     14.428571
7     14.571429
8     14.428571
9     13.857143
10    13.857143
11    13.000000
12    11.857143
13    11.428571
14    11.571429
15    12.571429
16    14.285714
17    15.000000
18    16.857143
dtype: float64

In [29]:
sv.quantile([0, .25, .5, .75, 1])

0.00     9.0
0.25    12.0
0.50    14.0
0.75    17.0
1.00    23.0
dtype: float64

In [30]:
sv.sample(25, replace=True)

14    14
11    10
3     14
15    18
2     13
15    18
17    19
4     16
8     11
15    18
14    14
12    11
17    19
2     13
11    10
14    14
3     14
11    10
6     15
7     13
6     15
15    18
8     11
14    14
10    14
dtype: int64

In [34]:
print(sv.to_csv(header=["val"], index_label="id"))

id,val
0,12
1,12
2,13
3,14
4,16
5,19
6,15
7,13
8,11
9,9
10,14
11,10
12,11
13,12
14,14
15,18
16,21
17,19
18,23

In [42]:
from pandas import DataFrame
dane = {'year': [2010, 2011, 2012, 2013, 2014, 2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022],
        'user1': [0, 0, 0, 0, 15, 49, 122, 341, 298, 319, 276, 307, 353],
        'user2': [743, 826, 756, 808, 634, 312, 95, 152, 112, 264, 317, 287, 172],
        'user3': [59, 91, 75, 158, 64, 49, 84, 78, 50, 68, 51, 108, 93]}
ac = DataFrame(dane, columns=['year', 'user1', 'user2', 'user3'])
ac

    year  user1  user2  user3
0   2010      0    743     59
1   2011      0    826     91
2   2012      0    756     75
3   2013      0    808    158
4   2014     15    634     64
5   2015     49    312     49
6   2016    122     95     84
7   2017    341    152     78
8   2018    298    112     50
9   2019    319    264     68
10  2020    276    317     51
11  2021    307    287    108
12  2022    353    172     93

In [43]:
for i in ac.index:
    print(f"Numer wiersza: {i}")
for c in ac.columns:
    print(f"Nazwa kolumny: {c}")

Numer wiersza: 0
Numer wiersza: 1
Numer wiersza: 2
Numer wiersza: 3
Numer wiersza: 4
Numer wiersza: 5
Numer wiersza: 6
Numer wiersza: 7
Numer wiersza: 8
Numer wiersza: 9
Numer wiersza: 10
Numer wiersza: 11
Numer wiersza: 12
Nazwa kolumny: year
Nazwa kolumny: user1
Nazwa kolumny: user2
Nazwa kolumny: user3

In [49]:
print(ac.dtypes)
print(type(ac.iloc[0]))
print(ac.dtypes['year'])

year     int64
user1    int64
user2    int64
user3    int64
dtype: object
<class 'pandas.core.series.Series'>
int64

In [50]:
print(ac.shape)

(13, 4)

In [54]:
ac.head()

   year  user1  user2  user3
0  2010      0    743     59
1  2011      0    826     91
2  2012      0    756     75
3  2013      0    808    158
4  2014     15    634     64

In [55]:
ac.at[10, 'user2'] = 123
print(ac.at[10, 'user2'])
print(ac.iat[10, 2])
print(ac.head(11))

123
123
    year  user1  user2  user3
0   2010      0    743     59
1   2011      0    826     91
2   2012      0    756     75
3   2013      0    808    158
4   2014     15    634     64
5   2015     49    312     49
6   2016    122     95     84
7   2017    341    152     78
8   2018    298    112     50
9   2019    319    264     68
10  2020    276    123     51

In [63]:
ac.loc[:4]

   year  user1  user2  user3
0  2010      0    743     59
1  2011      0    826     91
2  2012      0    756     75
3  2013      0    808    158
4  2014     15    634     64

In [65]:
ac.iloc[:4:2]

   year  user1  user2  user3
0  2010      0    743     59
2  2012      0    756     75

In [66]:
ac.insert(4, "user4", [1, 1, 0, 2, 9, 1, 4, 2, 2, 0, 2, 1, 3])
ac

    year  user1  user2  user3  user4
0   2010      0    743     59      1
1   2011      0    826     91      1
2   2012      0    756     75      0
3   2013      0    808    158      2
4   2014     15    634     64      9
5   2015     49    312     49      1
6   2016    122     95     84      4
7   2017    341    152     78      2
8   2018    298    112     50      2
9   2019    319    264     68      0
10  2020    276    123     51      2
11  2021    307    287    108      1
12  2022    353    172     93      3

In [ ]:
for label, content in ac.items():
    print(label)
    print(type(content))

In [ ]:
for content in ac:
    print(content)

In [ ]:
print(ac.tail(10))

In [67]:
ac.where(ac > 250)
#print(ac)

    year  user1  user2  user3  user4
0   2010    NaN  743.0    NaN    NaN
1   2011    NaN  826.0    NaN    NaN
2   2012    NaN  756.0    NaN    NaN
3   2013    NaN  808.0    NaN    NaN
4   2014    NaN  634.0    NaN    NaN
5   2015    NaN  312.0    NaN    NaN
6   2016    NaN    NaN    NaN    NaN
7   2017  341.0    NaN    NaN    NaN
8   2018  298.0    NaN    NaN    NaN
9   2019  319.0  264.0    NaN    NaN
10  2020  276.0    NaN    NaN    NaN
11  2021  307.0  287.0    NaN    NaN
12  2022  353.0    NaN    NaN    NaN

In [68]:
ac.mask(ac < 250, False)

    year  user1  user2  user3  user4
0   2010  False    743  False  False
1   2011  False    826  False  False
2   2012  False    756  False  False
3   2013  False    808  False  False
4   2014  False    634  False  False
5   2015  False    312  False  False
6   2016  False  False  False  False
7   2017    341  False  False  False
8   2018    298  False  False  False
9   2019    319    264  False  False
10  2020    276  False  False  False
11  2021    307    287  False  False
12  2022    353  False  False  False

In [69]:
print(ac.query('user1 > user2'))
print(ac[ac.user1 < ac.user2])

    year  user1  user2  user3  user4
6   2016    122     95     84      4
7   2017    341    152     78      2
8   2018    298    112     50      2
9   2019    319    264     68      0
10  2020    276    123     51      2
11  2021    307    287    108      1
12  2022    353    172     93      3
   year  user1  user2  user3  user4
0  2010      0    743     59      1
1  2011      0    826     91      1
2  2012      0    756     75      0
3  2013      0    808    158      2
4  2014     15    634     64      9
5  2015     49    312     49      1

In [70]:
print(ac.tail(3) + 100)
print(ac.tail(3) * 3)
print(ac.tail(3) / 10)
print(ac.tail(3) // 2)
print(ac.tail(3) % 10)

    year  user1  user2  user3  user4
10  2120    376    223    151    102
11  2121    407    387    208    101
12  2122    453    272    193    103
    year  user1  user2  user3  user4
10  6060    828    369    153      6
11  6063    921    861    324      3
12  6066   1059    516    279      9
     year  user1  user2  user3  user4
10  202.0   27.6   12.3    5.1    0.2
11  202.1   30.7   28.7   10.8    0.1
12  202.2   35.3   17.2    9.3    0.3
    year  user1  user2  user3  user4
10  1010    138     61     25      1
11  1010    153    143     54      0
12  1011    176     86     46      1
    year  user1  user2  user3  user4
10     0      6      3      1      2
11     1      7      7      8      1
12     2      3      2      3      3

In [71]:
print(ac.apply(lambda x: x%100 if x.name == "year" else x))
ac

    year  user1  user2  user3  user4
0     10      0    743     59      1
1     11      0    826     91      1
2     12      0    756     75      0
3     13      0    808    158      2
4     14     15    634     64      9
5     15     49    312     49      1
6     16    122     95     84      4
7     17    341    152     78      2
8     18    298    112     50      2
9     19    319    264     68      0
10    20    276    123     51      2
11    21    307    287    108      1
12    22    353    172     93      3

    year  user1  user2  user3  user4
0   2010      0    743     59      1
1   2011      0    826     91      1
2   2012      0    756     75      0
3   2013      0    808    158      2
4   2014     15    634     64      9
5   2015     49    312     49      1
6   2016    122     95     84      4
7   2017    341    152     78      2
8   2018    298    112     50      2
9   2019    319    264     68      0
10  2020    276    123     51      2
11  2021    307    287    108      1
12  2022    353    172     93      3

In [ ]:
salaries = {'stażysta': [2294, 2417, 2538], 'kontraktowy': [2361, 2487, 2611], 'mianowany': [2681, 2824, 2965], 'dyplomowany': [3149, 3317, 3483]}
factor = {'stażysta': [2, 2, 5], 'kontraktowy': [.5, .5, 1], 'mianowany': [2, 2, .5], 'dyplomowany': [2, 3, 4]}
years = [2017,2018,2019]
a = DataFrame(salaries, index=years)
b = DataFrame(factor, index=years)
print(a)
print(b)
print(a*b)

In [ ]:
print(a.agg(['mean', 'max', 'std']))

In [ ]:
dane = [1, 2, 3, 10, 20, 30, 100, 200, 300]
czas = [2017, 2018, 2019, 2017, 2018, 2019, 2017, 2018, 2019]
c = DataFrame({'date': czas, 'data': dane})
print(c)
print(c.groupby('date').sum())
print(c.groupby('date').transform('sum'))

In [ ]:
print(a.T)
print(a.T.std())

In [ ]:
print(c.drop_duplicates(subset='date'))
c

In [ ]:
d = DataFrame([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
print("obiekt d:")
print(d)
print("transpozycja obiektu d:")
print(d.T)
print("mnożenie macierzy d i d.T:")
print(d.dot(d.T))

In [ ]:
import numpy as np
macierz = d.dot(d.T).to_numpy()
print(macierz)
print(np.linalg.det(macierz))